<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Commercial Proposal - Lead Panther CRM</title>
    <x-ui.vite-assets />
</head>
<body class="bg-canvas text-ink min-h-screen p-6 flex flex-col items-center">
    <div class="max-w-2xl w-full bg-surface rounded-card border border-border p-8 shadow-lg space-y-6">
        <div class="flex items-center justify-between border-b border-border pb-4">
            <div>
                <h1 class="text-xl font-bold text-ink">OFFICIAL COMMERCIAL PROPOSAL</h1>
                <p class="text-xs text-muted">Generated by Lead Panther Real Estate CRM</p>
            </div>
            <span class="px-3 py-1 bg-green-50 text-green-700 text-xs font-bold rounded-pill">VERIFIED PROPOSAL</span>
        </div>

        <div class="grid grid-cols-2 gap-4 text-xs">
            <div>
                <span class="text-muted">Client Name:</span>
                <p class="font-bold text-ink">{{ $lead->name ?? 'Client' }}</p>
            </div>
            <div>
                <span class="text-muted">Mobile / Email:</span>
                <p class="font-bold text-ink">{{ $lead->mobile ?? '' }} | {{ $lead->email ?? '' }}</p>
            </div>
            <div>
                <span class="text-muted">Selected Unit:</span>
                <p class="font-bold text-ink">{{ $unit->unit_number ?? 'Unit #'.$proposal->project_unit_id }}</p>
            </div>
            <div>
                <span class="text-muted">Proposal Validity:</span>
                <p class="font-bold text-ink">{{ \Carbon\Carbon::parse($proposal->validity_date)->format('M d, Y') }}</p>
            </div>
        </div>

        <div class="bg-canvas p-4 rounded-card border border-border space-y-2">
            <div class="flex justify-between text-xs font-bold">
                <span>Base Unit Price:</span>
                <span>₹{{ number_format($proposal->price ?? 0) }}</span>
            </div>
            <div class="flex justify-between text-xs text-green-600 font-bold">
                <span>Special Discount:</span>
                <span>- ₹{{ number_format($proposal->discount ?? 0) }}</span>
            </div>
            <div class="flex justify-between text-sm font-extrabold text-ink border-t border-border pt-2">
                <span>Net Payable Amount:</span>
                <span>₹{{ number_format($proposal->price - $proposal->discount) }}</span>
            </div>
        </div>

        @if($proposal->terms)
            <div class="text-xs space-y-1">
                <span class="font-bold text-ink">Terms & Payment Schedule:</span>
                <p class="text-muted bg-canvas p-3 rounded-lg border border-border">{{ $proposal->terms }}</p>
            </div>
        @endif

        <div class="text-[11px] text-muted text-center pt-4 border-t border-border">
            Viewed online on {{ now()->format('M d, Y H:i:s') }}. Thank you for choosing Lead Panther CRM properties.
        </div>
    </div>
</body>
</html>
